version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-only:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint:lib
            - run: npm run test:lib
      - store_artifacts:
            path: coverage
  publish:
    executor:
      name: node/default
    steps:
        - checkout
        - run:
            name: Publish to NPM
            command: |
                npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                npm publish

workflows:
    build-namefully:
      jobs:
        - build-only:
            filters:
                branches:
                    only:
                        - master
